// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`
/* eslint-disable no-undef */

interface CloudflareEnv {
	NEXT_CACHE_WORKERS_KV: KVNamespace;
	ASSETS: Fetcher;
}
